# Generated by Django 5.2.6 on 2025-09-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hall_capacity_hall_description_alter_hall_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('club', 'Club'), ('admin', 'Admin'), ('hall_incharge', 'Hall in Charge'), ('principal', 'Principal')], default='student', max_length=20),
        ),
    ]
