# Generated by Django 5.2.6 on 2025-09-18 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='Princi_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='dean_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='event', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='request_type',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('permissions', 'Permissions')], default='permission', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('reserved', 'Reserved'), ('hall_approved', 'Hall Approved'), ('principal_approved', 'Principal Appoved'), ('forward to dean', 'Forward to Dean'), ('Dean approved', 'Approved by Dean'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
