# Generated by Django 5.2.6 on 2025-11-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
